import { Product, Category } from "./types";

export const categories: Category[] = [
  { id: "electronics", name: "Electronics", slug: "electronics", image: "https://picsum.photos/seed/electronics/400/400", count: 8 },
  { id: "fashion", name: "Fashion", slug: "fashion", image: "https://picsum.photos/seed/fashion/400/400", count: 8 },
  { id: "home-garden", name: "Home & Garden", slug: "home-garden", image: "https://picsum.photos/seed/home/400/400", count: 6 },
  { id: "sports", name: "Sports & Outdoors", slug: "sports", image: "https://picsum.photos/seed/sports/400/400", count: 6 },
  { id: "beauty", name: "Beauty & Health", slug: "beauty", image: "https://picsum.photos/seed/beauty/400/400", count: 6 },
  { id: "accessories", name: "Accessories", slug: "accessories", image: "https://picsum.photos/seed/accessories/400/400", count: 6 },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Earbuds Pro",
    slug: "wireless-bluetooth-earbuds-pro",
    description: "Premium wireless earbuds with active noise cancellation, 24-hour battery life, and ergonomic design. Features Bluetooth 5.3, IPX5 water resistance, and touch controls. Perfect for workouts, commuting, and daily use.",
    price: 49.99,
    originalPrice: 89.99,
    images: [
      "https://picsum.photos/seed/earbuds1/600/600",
      "https://picsum.photos/seed/earbuds2/600/600",
      "https://picsum.photos/seed/earbuds3/600/600",
    ],
    category: "electronics",
    subcategory: "Audio",
    rating: 4.7,
    reviews: 2341,
    inStock: true,
    features: [
      "Active Noise Cancellation (ANC)",
      "Bluetooth 5.3 connectivity",
      "24-hour battery life with case",
      "IPX5 water resistant",
      "Touch controls with voice assistant",
      "Ergonomic fit with 3 ear tip sizes",
    ],
    specifications: {
      "Battery Life": "8 hours (32h with case)",
      "Driver Size": "13mm",
      "Bluetooth": "5.3",
      "Water Resistance": "IPX5",
      "Weight": "4.5g per earbud",
      "Charging": "USB-C / Wireless",
    },
  },
  {
    id: "2",
    name: "Smart Fitness Watch Ultra",
    slug: "smart-fitness-watch-ultra",
    description: "Advanced smartwatch with 1.9-inch AMOLED display, GPS tracking, heart rate monitor, blood oxygen sensor, and 100+ workout modes. 14-day battery life. Compatible with iOS and Android.",
    price: 79.99,
    originalPrice: 149.99,
    images: [
      "https://picsum.photos/seed/watch1/600/600",
      "https://picsum.photos/seed/watch2/600/600",
      "https://picsum.photos/seed/watch3/600/600",
    ],
    category: "electronics",
    subcategory: "Wearables",
    rating: 4.5,
    reviews: 1876,
    inStock: true,
    features: [
      "1.9\" AMOLED always-on display",
      "GPS + GLONASS positioning",
      "Heart rate & blood oxygen monitor",
      "Sleep tracking & stress monitoring",
      "100+ workout modes",
      "14-day battery life",
    ],
    specifications: {
      Display: "1.9\" AMOLED 320x386",
      Battery: "14 days typical",
      Sensors: "HR, SpO2, Accelerometer, Gyroscope",
      Connectivity: "Bluetooth 5.2, GPS",
      "Water Resistance": "5 ATM",
      Compatibility: "iOS 12+ / Android 6+",
    },
  },
  {
    id: "3",
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    description: "Powerful portable speaker with 360-degree sound, deep bass, and 20-hour battery. IPX7 waterproof rating. Built-in microphone for calls. Perfect for outdoor adventures.",
    price: 34.99,
    originalPrice: 59.99,
    images: [
      "https://picsum.photos/seed/speaker1/600/600",
      "https://picsum.photos/seed/speaker2/600/600",
    ],
    category: "electronics",
    subcategory: "Audio",
    rating: 4.6,
    reviews: 3210,
    inStock: true,
    features: [
      "360-degree surround sound",
      "20-hour playtime",
      "IPX7 waterproof",
      "Built-in microphone",
      "TWS pair two speakers",
      "USB-C charging",
    ],
    specifications: {
      Output: "30W peak",
      "Battery Life": "20 hours",
      "Waterproof": "IPX7",
      Bluetooth: "5.0",
      Weight: "680g",
      Dimensions: "22 x 8 x 8 cm",
    },
  },
  {
    id: "4",
    name: "4K Webcam with Ring Light",
    slug: "4k-webcam-ring-light",
    description: "Professional 4K webcam with built-in adjustable ring light, auto-focus, and noise-canceling dual microphones. Perfect for streaming, video calls, and content creation.",
    price: 44.99,
    originalPrice: 79.99,
    images: [
      "https://picsum.photos/seed/webcam1/600/600",
      "https://picsum.photos/seed/webcam2/600/600",
    ],
    category: "electronics",
    subcategory: "Computer Accessories",
    rating: 4.4,
    reviews: 1543,
    inStock: true,
    features: [
      "4K@30fps / 1080p@60fps",
      "Built-in adjustable ring light",
      "Auto-focus with face tracking",
      "Dual noise-canceling mics",
      "Plug-and-play USB-C",
      "Privacy cover included",
    ],
    specifications: {
      Resolution: "4K (3840x2160)",
      "Frame Rate": "30fps (4K), 60fps (1080p)",
      "Field of View": "90°",
      Microphone: "Dual stereo",
      Connection: "USB-C / USB-A",
      "Light Temperature": "3000K-6500K",
    },
  },
  {
    id: "5",
    name: "Wireless Charging Station Pad",
    slug: "wireless-charging-station-pad",
    description: "3-in-1 wireless charging station for iPhone, Apple Watch, and AirPods. Fast charging 15W output. Anti-slip design with LED indicator. Compatible with all Qi-enabled devices.",
    price: 29.99,
    originalPrice: 49.99,
    images: [
      "https://picsum.photos/seed/charger1/600/600",
      "https://picsum.photos/seed/charger2/600/600",
    ],
    category: "electronics",
    subcategory: "Charging",
    rating: 4.3,
    reviews: 987,
    inStock: true,
    features: [
      "3-in-1 charging for phone, watch, earbuds",
      "15W fast wireless charging",
      "LED charging indicators",
      "Anti-slip silicone surface",
      "Overcharge protection",
      "Compact foldable design",
    ],
    specifications: {
      "Phone Output": "15W max",
      "Watch Output": "5W",
      "Earbuds Output": "5W",
      Input: "9V/2A, 12V/1.5A",
      Compatibility: "All Qi devices",
      Material: "ABS + Silicone",
    },
  },
  {
    id: "6",
    name: "Premium Cotton Oversized T-Shirt",
    slug: "premium-cotton-oversized-tshirt",
    description: "Comfortable oversized t-shirt made from 100% ring-spun cotton. Pre-shrunk fabric with reinforced stitching. Available in 10+ colors. Modern streetwear style.",
    price: 19.99,
    originalPrice: 34.99,
    images: [
      "https://picsum.photos/seed/tshirt1/600/600",
      "https://picsum.photos/seed/tshirt2/600/600",
    ],
    category: "fashion",
    subcategory: "Tops",
    rating: 4.6,
    reviews: 4567,
    inStock: true,
    features: [
      "100% ring-spun cotton",
      "Pre-shrunk fabric",
      "Oversized modern fit",
      "Reinforced double-stitching",
      "10+ vibrant colors",
      "Tear-away label for comfort",
    ],
    specifications: {
      Material: "100% Cotton",
      Weight: "220 GSM",
      Fit: "Oversized",
      Sizes: "S - 5XL",
      "Neck Style": "Crew neck",
      Care: "Machine washable",
    },
  },
  {
    id: "7",
    name: "Slim Fit Casual Blazer",
    slug: "slim-fit-casual-blazer",
    description: "Versatile slim-fit blazer for casual and semi-formal occasions. Stretch fabric blend with 2-button closure, notch lapels, and interior pockets. Perfect for smart casual looks.",
    price: 59.99,
    originalPrice: 99.99,
    images: [
      "https://picsum.photos/seed/blazer1/600/600",
      "https://picsum.photos/seed/blazer2/600/600",
    ],
    category: "fashion",
    subcategory: "Outerwear",
    rating: 4.4,
    reviews: 1234,
    inStock: true,
    features: [
      "Stretch fabric for comfort",
      "2-button front closure",
      "Notch lapels",
      "3 exterior + 2 interior pockets",
      "Fully lined",
      "Wrinkle-resistant fabric",
    ],
    specifications: {
      Material: "65% Polyester, 33% Viscose, 2% Elastane",
      Lining: "100% Polyester",
      Closure: "2-button",
      Lapels: "Notch",
      Pockets: "5 total",
      Care: "Dry clean recommended",
    },
  },
  {
    id: "8",
    name: "Classic Leather Crossbody Bag",
    slug: "classic-leather-crossbody-bag",
    description: "Genuine leather crossbody bag with adjustable strap, multiple compartments, and RFID-blocking pocket. Vintage design meets modern functionality. Perfect for travel and daily use.",
    price: 39.99,
    originalPrice: 69.99,
    images: [
      "https://picsum.photos/seed/bag1/600/600",
      "https://picsum.photos/seed/bag2/600/600",
      "https://picsum.photos/seed/bag3/600/600",
    ],
    category: "fashion",
    subcategory: "Bags",
    rating: 4.7,
    reviews: 2890,
    inStock: true,
    features: [
      "Genuine cowhide leather",
      "Adjustable crossbody strap",
      "RFID-blocking card pocket",
      "Multiple interior compartments",
      "Secure zipper closure",
      "Vintage brass hardware",
    ],
    specifications: {
      Material: "Genuine cowhide leather",
      Dimensions: "25 x 18 x 8 cm",
      "Strap Length": "120 cm (adjustable)",
      Weight: "450g",
      Closure: "Zipper + magnetic snap",
      Pockets: "3 interior, 1 exterior, 1 RFID",
    },
  },
  {
    id: "9",
    name: "Crystal Clear Unisex Sunglasses",
    slug: "crystal-clear-unisex-sunglasses",
    description: "Trendy oversized sunglasses with UV400 protection. Lightweight acetate frame with spring hinges. Unisex design suitable for all face shapes. Includes hard case and microfiber cloth.",
    price: 24.99,
    originalPrice: 44.99,
    images: [
      "https://picsum.photos/seed/sunglasses1/600/600",
      "https://picsum.photos/seed/sunglasses2/600/600",
    ],
    category: "accessories",
    subcategory: "Eyewear",
    rating: 4.5,
    reviews: 3456,
    inStock: true,
    features: [
      "UV400 full protection",
      "Lightweight acetate frame",
      "Spring hinges for comfort",
      "Unisex oversized design",
      "Scratch-resistant lenses",
      "Includes hard case & cloth",
    ],
    specifications: {
      "Lens Material": "Polycarbonate",
      "Frame Material": "Acetate",
      "UV Protection": "UV400 (100%)",
      "Lens Width": "54mm",
      "Frame Width": "145mm",
      Weight: "38g",
    },
  },
  {
    id: "10",
    name: "Stainless Steel Water Bottle 1L",
    slug: "stainless-steel-water-bottle",
    description: "Double-wall vacuum insulated water bottle. Keeps drinks cold 24h or hot 12h. 1-liter capacity. BPA-free, leak-proof lid with carry loop. Eco-friendly alternative to plastic bottles.",
    price: 22.99,
    originalPrice: 39.99,
    images: [
      "https://picsum.photos/seed/bottle1/600/600",
      "https://picsum.photos/seed/bottle2/600/600",
    ],
    category: "sports",
    subcategory: "Hydration",
    rating: 4.8,
    reviews: 5678,
    inStock: true,
    features: [
      "Double-wall vacuum insulation",
      "24h cold / 12h hot retention",
      "1L (32oz) capacity",
      "BPA-free & leak-proof",
      "Carry loop on lid",
      "Powder-coated finish",
    ],
    specifications: {
      Capacity: "1L (32 oz)",
      Material: "18/8 Stainless Steel",
      Insulation: "Double-wall vacuum",
      "Temperature Retention": "Cold 24h / Hot 12h",
      Weight: "380g",
      Dimensions: "26 x 7.5 cm",
    },
  },
  {
    id: "11",
    name: "Professional Yoga Mat Extra Thick",
    slug: "professional-yoga-mat-extra-thick",
    description: "Premium extra-thick yoga mat with alignment lines. Non-slip TPE material with excellent cushioning. Includes carrying strap. Ideal for yoga, pilates, and floor exercises.",
    price: 32.99,
    originalPrice: 54.99,
    images: [
      "https://picsum.photos/seed/yogamat1/600/600",
      "https://picsum.photos/seed/yogamat2/600/600",
    ],
    category: "sports",
    subcategory: "Fitness",
    rating: 4.6,
    reviews: 2345,
    inStock: true,
    features: [
      "12mm extra thick cushion",
      "Alignment line system",
      "Non-slip TPE material",
      "Carrying strap included",
      "Eco-friendly & non-toxic",
      "Moisture resistant surface",
    ],
    specifications: {
      Thickness: "12mm (0.47\")",
      Dimensions: "183 x 61 cm",
      Material: "TPE (eco-friendly)",
      Weight: "1.2 kg",
      Color: "Navy / Purple / Teal",
      "Includes": "Carrying strap",
    },
  },
  {
    id: "12",
    name: "LED Desk Lamp with Wireless Charger",
    slug: "led-desk-lamp-wireless-charger",
    description: "Modern LED desk lamp with built-in 15W wireless charging pad. Touch control with 5 brightness levels and 3 color temperatures. USB-A charging port. Eye-care technology.",
    price: 39.99,
    originalPrice: 69.99,
    images: [
      "https://picsum.photos/seed/lamp1/600/600",
      "https://picsum.photos/seed/lamp2/600/600",
    ],
    category: "home-garden",
    subcategory: "Lighting",
    rating: 4.5,
    reviews: 1876,
    inStock: true,
    features: [
      "Built-in 15W wireless charger",
      "5 brightness levels, 3 color temps",
      "Touch control panel",
      "USB-A charging port",
      "Flicker-free eye-care light",
      "Flexible adjustable gooseneck",
    ],
    specifications: {
      "Light Source": "48 LED beads",
      Brightness: "5 levels (200-1200 lux)",
      "Color Temperature": "3000K-6500K",
      "Wireless Charger": "15W Qi",
      "USB Port": "5V/2.1A",
      "Power": "12W",
    },
  },
  {
    id: "13",
    name: "Hydrolyzed Collagen Peptides Powder",
    slug: "hydrolyzed-collagen-peptides",
    description: "Type I & III hydrolyzed collagen peptides. Unflavored powder that dissolves instantly in hot or cold liquids. Supports skin elasticity, joint health, hair, and nails. 20g protein per serving.",
    price: 27.99,
    originalPrice: 44.99,
    images: [
      "https://picsum.photos/seed/collagen1/600/600",
      "https://picsum.photos/seed/collagen2/600/600",
    ],
    category: "beauty",
    subcategory: "Supplements",
    rating: 4.7,
    reviews: 4123,
    inStock: true,
    features: [
      "Type I & III hydrolyzed collagen",
      "20g protein per serving",
      "Unflavored - mixes with anything",
      "Supports skin, hair, nails & joints",
      "Grass-fed, pasture-raised",
      "No additives or preservatives",
    ],
    specifications: {
      "Serving Size": "20g (2 scoops)",
      Protein: "20g per serving",
      Collagen: "Type I & III",
      Source: "Grass-fed bovine",
      Flavor: "Unflavored",
      "Package Size": "500g (25 servings)",
    },
  },
  {
    id: "14",
    name: "Knife Sharpening Stone Kit",
    slug: "knife-sharpening-stone-kit",
    description: "Professional whetstone sharpening kit with 4 grit levels (400/1000/3000/8000). Includes bamboo base, angle guide, leather strop, and honing oil. Restore any blade to razor sharpness.",
    price: 25.99,
    originalPrice: 44.99,
    images: [
      "https://picsum.photos/seed/knifestone1/600/600",
      "https://picsum.photos/seed/knifestone2/600/600",
    ],
    category: "home-garden",
    subcategory: "Kitchen",
    rating: 4.6,
    reviews: 1654,
    inStock: true,
    features: [
      "4 grit levels: 400/1000/3000/8000",
      "Non-slip bamboo base",
      "Angle guide included",
      "Leather strop for finishing",
      "Honing oil included",
      "Suitable for all blade types",
    ],
    specifications: {
      "Grit Levels": "400 / 1000 / 3000 / 8000",
      "Stone Material": "Corundum",
      "Base": "Natural bamboo",
      "Includes": "Base, angle guide, strop, oil",
      Dimensions: "18 x 6 x 2.5 cm (per stone)",
      Weight: "900g (total kit)",
    },
  },
  {
    id: "15",
    name: "Essential Oil Diffuser Humidifier",
    slug: "essential-oil-diffuser-humidifier",
    description: "Ultrasonic essential oil diffuser with 300ml capacity. LED mood lighting with 7 color options. Auto shut-off safety. Whisper-quiet operation (under 25dB). Coverage up to 30m².",
    price: 21.99,
    originalPrice: 36.99,
    images: [
      "https://picsum.photos/seed/diffuser1/600/600",
      "https://picsum.photos/seed/diffuser2/600/600",
    ],
    category: "home-garden",
    subcategory: "Home Decor",
    rating: 4.5,
    reviews: 2890,
    inStock: true,
    features: [
      "Ultrasonic cool mist technology",
      "300ml tank (8-10 hours runtime)",
      "7-color LED mood lighting",
      "Auto shut-off when empty",
      "Whisper quiet (under 25dB)",
      "Coverage up to 30m²",
    ],
    specifications: {
      Capacity: "300ml",
      "Run Time": "8-10 hours",
      Coverage: "Up to 30m²",
      Noise: "<25dB",
      Material: "PP + ABS",
      Power: "12W",
    },
  },
  {
    id: "16",
    name: "Resistance Bands Set - 5 Pack",
    slug: "resistance-bands-set",
    description: "Set of 5 resistance bands with different tension levels (10-50 lbs). Natural latex with reinforced edges. Includes carrying bag, door anchor, and exercise guide. Perfect for home workouts.",
    price: 18.99,
    originalPrice: 32.99,
    images: [
      "https://picsum.photos/seed/bands1/600/600",
      "https://picsum.photos/seed/bands2/600/600",
    ],
    category: "sports",
    subcategory: "Fitness",
    rating: 4.6,
    reviews: 3789,
    inStock: true,
    features: [
      "5 resistance levels (10-50 lbs)",
      "Natural latex with reinforced edges",
      "Carrying bag included",
      "Door anchor for versatile exercises",
      "Digital exercise guide",
      "Non-slip surface design",
    ],
    specifications: {
      "Resistance Levels": "10, 20, 30, 40, 50 lbs",
      Material: "Natural latex",
      "Total Length": "120 cm each",
      "Includes": "5 bands, bag, anchor, guide",
      Weight: "680g (set)",
      Warranty: "12 months",
    },
  },
  {
    id: "17",
    name: "Retro Mini Fridge 4L",
    slug: "retro-mini-fridge-4l",
    description: "Compact retro-style mini fridge with 4L capacity. Cools up to 20°C below ambient temperature. Perfect for skincare, beverages, or snacks at your desk. USB-powered.",
    price: 45.99,
    originalPrice: 74.99,
    images: [
      "https://picsum.photos/seed/fridge1/600/600",
      "https://picsum.photos/seed/fridge2/600/600",
    ],
    category: "home-garden",
    subcategory: "Kitchen",
    rating: 4.3,
    reviews: 1234,
    inStock: true,
    features: [
      "4L capacity (6 cans)",
      "Retro design with chrome handle",
      "Cools 20°C below ambient",
      "USB-powered (5V/2A)",
      "Silent operation",
      "Reversible door hinge",
    ],
    specifications: {
      Capacity: "4L (6 x 330ml cans)",
      "Cooling Type": "Thermoelectric",
      "Temperature Drop": "20°C below ambient",
      "Power": "5V/2A (USB)",
      Noise: "<20dB",
      Dimensions: "25 x 18 x 20 cm",
    },
  },
  {
    id: "18",
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description: "Professional-grade Vitamin C serum with hyaluronic acid and vitamin E. 20% L-Ascorbic Acid formulation. Reduces dark spots, evens skin tone, and boosts collagen production.",
    price: 16.99,
    originalPrice: 29.99,
    images: [
      "https://picsum.photos/seed/serum1/600/600",
      "https://picsum.photos/seed/serum2/600/600",
    ],
    category: "beauty",
    subcategory: "Skincare",
    rating: 4.7,
    reviews: 5678,
    inStock: true,
    features: [
      "20% L-Ascorbic Acid (Vitamin C)",
      "Hyaluronic acid for hydration",
      "Vitamin E antioxidant protection",
      "Reduces dark spots & hyperpigmentation",
      "Boosts collagen production",
      "Lightweight, fast-absorbing formula",
    ],
    specifications: {
      "Active Ingredient": "20% L-Ascorbic Acid",
      Volume: "30ml (1 oz)",
      "Other Key Ingredients": "Hyaluronic Acid, Vitamin E, Ferulic Acid",
      "Skin Type": "All skin types",
      "Shelf Life": "12 months after opening",
      Application: "Apply 3-4 drops AM/PM",
    },
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.rating >= 4.6).slice(0, 8);
}

export function formatPrice(price: number): string {
  return `$${price.toFixed(2)}`;
}

export function formatEGP(priceUSD: number, rate: number): string {
  return `ج.م ${(priceUSD * rate).toFixed(2)}`;
}

export function displayPrice(priceUSD: number, rate: number): string {
  return rate === 1 ? `$${priceUSD.toFixed(2)}` : `ج.م ${(priceUSD * rate).toFixed(2)}`;
}
